# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
show_date: false
main:
  - name: Vision
    url: '#about'
    weight: 10
  - name: Members
    url: '#members'
    weight: 20
  - name: Publications
    url: '#featured'
    weight: 40
  - name: Resources
    url: '#resources'
    weight: 50
  - name: Videos
    parent: Resources
    url: '#Videos'
    weight: 10
  - name: Tools
    parent: Resources
    url: '#tools'
    weight: 20
  - name: Contact
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
