# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Vision
    url: '#about'
    weight: 10
  - name: Members
    url: '#members'
    weight: 20
  - name: Publications
    url: '#featured'
    weight: 40
  - name: Resources
    url: '#resources'
    weight: 50
  - name: Demos
    parent: Resources
    url: '#demos'
    weight: 10
  - name: Tools
    parent: Resources
    url: '#tools'
    weight: 20
  - name: Contact
    url: '#contact'
    weight: 60
  - name: License
    url: '#license'
    weight: 70
    
license:
  - content: 'Trust4AI is licensed under the terms of the GPL-3.0 license. Funded by the European Union. Views and opinions expressed are however those of the author(s) only and do not necessarily reflect those of the European Union or European Commission. Neither the European Union nor the granting authority can be held responsible for them. Funded within the framework of the NGI Search project under grant agreement No 101069364.'

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
